### ISSUE TITLE
[Issue] AGS stuck at one color

### ISSUE THREAD

**Issue by PlexILIghT** [end-4/dots-hyprland#1023]
- Yes. I have read the Usage and Troubleshooting pages of the wiki: https://end-4.github.io/dots-hyprland-wiki/en/i-i/04troubleshooting/
- Yes. I have made sure that both my config and system packages are up to date
- Linux distro: Arch

---
## The issue
So, after fixing the ```@import 'material';``` line, and problem that only I faced #1013
changing wallpaper does these 3 things:
1. Changes wallpaper
2. Invokes the "Color schemes" widget
3. Changes terminal colors.
### A big BUT.
It does not change the color scheme. The whole color widget does not change nothing in the AGS. However, the terminal is damn chillin'. He's good boy changing colors even by changing "Scheme styles". And actually nautilus and other stuff, like VSCode top bar. Screenshots are attached.

![image](https://github.com/user-attachments/assets/aaf0014d-1d7b-4051-beb0-4bab4ef0cfd2)
![image](https://github.com/user-attachments/assets/53230519-7a80-4b48-bfb7-f35b231d0fe1)

<details>
<summary>Logs</summary>
First is pkill ags; ags
Actually nothing to watch here, as those are cached web images and does not associate with local files nor desktop.
Next ones is ags scripts run in terminal.

```plain
Traceback (most recent call last):
  File "/home/u200b/.config/ags/scripts/color_generation/generate_colors_material.py", line 65, in <module>
    image = Image.open(args.path)
  File "/usr/lib/python3.13/site-packages/PIL/Image.py", line 3536, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file '/home/u200b/.cache/ags/media/d814e7ec150fdf5d4e7dac563390e12269573208'
Traceback (most recent call last):
  File "/home/u200b/.config/ags/scripts/color_generation/generate_colors_material.py", line 65, in <module>
    image = Image.open(args.path)
  File "/usr/lib/python3.13/site-packages/PIL/Image.py", line 3536, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file '/home/u200b/.cache/ags/media/d814e7ec150fdf5d4e7dac563390e12269573208'

Gjs-Console-Message: 14:35:52.576: [LOG] Styles loaded

Gjs-Console-Message: 14:35:54.778: [LOG] Styles loaded

Gjs-Console-Message: 14:35:59.232: [LOG] Styles loaded

Gjs-Console-Message: 14:36:02.527: [LOG] Styles loaded
```

```plain
cd /.config/ags/scripts/color_generation
./applycolor.sh
undefined
undefined
[Gradience] INFO: Preset Material3_Generated applied successfully for Gtk 3 and Gtk 4 applications.
[Gradience] INFO: In order for changes to take full effect, you need to log out.
```
No, neither logout neither reboot or shutdown are not helping.
## Also, fd is not installed😁.
```plain
./randomwall.sh 
./randomwall.sh: line 4: fd: command not found
Aborted
```
</details>

**Comment by mohak34** [comment]
yes having the same issue the ags bar does not change w.r.t the wallpaper .

@PlexILIghT how do you have transparency enabled. if i try to enable it, my whole setup breaks

**Comment by PlexILIghT** [comment]
@mohak34
I enabled and configured transparency in ~/.config/hypr/custom folder (also can be done in /.config/hypr/hyprland, but better in custom/). File "rules.conf". Add ```windowrule = opacity 1 0.89, .*``` for focused window to be solid and unfocused to be transparent.
If errors, then next ones will help:
Check #1010.
If not, then
#1011 -  check python modules installed - install/reinstall them. If nothing changed, then this is a dual python installationn issue. #1013 check pythons and scripts (ags) logs. In my case I had two pythons installed and package managers were pointing at different python. You can also type ```pkill ags; ags``` to see if ags has something to say. Same for scripts. They are in ~/.config/ags/scripts/color_generation, launch them in terminal and see what's wrong

**Comment by PlexILIghT** [comment]
Solution from AlpSha in issue #1033 worked for me. Putting color generation module in venv resolves it. For it to work correctly you need to change back line ```@import 'material'; ```
