### ISSUE TITLE
[Issue] ags bar icon not working

### ISSUE THREAD

**Issue by idadwind1** [end-4/dots-hyprland#1030]
- I have read the Usage and Troubleshooting pages of the wiki: https://end-4.github.io/dots-hyprland-wiki/en/i-i/04troubleshooting/
- I have made sure that both my config and system packages are up to date
- Linux distro: arch linux

---
## The issue

ags bar is showing text instead of icons.
![image](https://github.com/user-attachments/assets/9c47bbf5-9e37-4600-a339-561f715bffb2)
I've tried to reinstall material symbol font:
```
$ ls /usr/share/fonts/
100dpi/                 encodings/                         MaterialIcons-Regular.ttf         misc/      smiley-sans/       ttf-material-symbols-variable/
75dpi/                  gnu-free/                          MaterialIconsRound-Regular.otf    noto/      TTF/               ttf-readex-pro/
adobe-source-code-pro/  gsfonts/                           MaterialIconsSharp-Regular.otf    noto-cjk/  ttf-gabarito-git/  wenquanyi/
cantarell/              MaterialIconsOutlined-Regular.otf  MaterialIconsTwoTone-Regular.otf  OTF/       ttf-maple-beta/
```
Ive tried #1010.
Editing `@import 'material';` in ~/.config/ags/scss/main.scss to `@import './fallback/material';` does nothing

<details>
<summary>Logs</summary>

ags gave the following:
```plain
(com.github.Aylur.ags:4904): Gjs-CRITICAL **: 13:28:04.990: JS ERROR: TypeError: section.get_file() is null
applyCss/<@resource:///com/github/Aylur/ags/app.js:73:34
applyCss@resource:///com/github/Aylur/ags/app.js:81:29
applyStyle@file:///home/idadwind/.config/ags/init.js:26:13
globalThis.handleStyles@file:///home/idadwind/.config/ags/init.js:29:5
@file:///home/idadwind/.config/ags/config.js:37:13
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:263:34


(com.github.Aylur.ags:4904): Gjs-Console-WARNING **: 13:28:05.059: Error: can't assign "chromium-browser" as icon, it is not a file nor a named icon
set icon@resource:///com/github/Aylur/ags/widgets/icon.js:45:30
_handleParamProp@resource:///com/github/Aylur/ags/widgets/widget.js:124:13
Icon@resource:///com/github/Aylur/ags/widgets/icon.js:25:14
newIcon@resource:///com/github/Aylur/ags/widgets/icon.js:8:12
ElementTile@file:///home/idadwind/.config/ags/modules/cheatsheet/periodictable.js:26:32
default/mainBoard<.children</<.children<@file:///home/idadwind/.config/ags/modules/cheatsheet/periodictable.js:62:58
default/mainBoard<.children<@file:///home/idadwind/.config/ags/modules/cheatsheet/periodictable.js:62:27
default@file:///home/idadwind/.config/ags/modules/cheatsheet/periodictable.js:60:33
SheetContent/sheetContents[id]<.children<@file:///home/idadwind/.config/ags/modules/cheatsheet/main.js:82:48
SheetContent@file:///home/idadwind/.config/ags/modules/cheatsheet/main.js:82:31
default@file:///home/idadwind/.config/ags/modules/cheatsheet/main.js:91:32
forMonitors@file:///home/idadwind/.config/ags/config.js:29:24
Windows@file:///home/idadwind/.config/ags/config.js:47:5
@file:///home/idadwind/.config/ags/config.js:75:14
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:263:34
  
Gtk.CssProviderError: <data>:1:0Expected a valid selector

(com.github.Aylur.ags:4904): Gjs-Console-WARNING **: 13:28:05.420: Error: can't assign "spotify" as icon, it is not a file nor a named icon
set icon@resource:///com/github/Aylur/ags/widgets/icon.js:45:30
AppVolume/setup/<@file:///home/idadwind/.config/ags/modules/sideright/centermodules/audiocontrols.js:18:52
hook/<@resource:///com/github/Aylur/ags/widgets/widget.js:43:25
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:263:34
  

(com.github.Aylur.ags:4904): Gjs-CRITICAL **: 13:28:05.707: JS ERROR: TypeError: section.get_file() is null
applyCss/<@resource:///com/github/Aylur/ags/app.js:73:34
applyCss@resource:///com/github/Aylur/ags/app.js:81:29
CoverArt/updateCover/<@file:///home/idadwind/.config/ags/modules/indicators/musiccontrols.js:218:29
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:263:34

Gtk.CssProviderError: <data>:1:0Expected a valid selector

(com.github.Aylur.ags:4904): Gjs-CRITICAL **: 13:28:22.391: JS ERROR: TypeError: section.get_file() is null
applyCss/<@resource:///com/github/Aylur/ags/app.js:73:34
applyCss@resource:///com/github/Aylur/ags/app.js:81:29
CoverArt/updateCover/<@file:///home/idadwind/.config/ags/modules/indicators/musiccontrols.js:218:29
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:263:34

Gtk.CssProviderError: <data>:1:0Expected a valid selector

(com.github.Aylur.ags:4904): Gjs-Console-WARNING **: 13:30:03.262: Error: can't assign "spotify" as icon, it is not a file nor a named icon
set icon@resource:///com/github/Aylur/ags/widgets/icon.js:45:30
AppVolume/setup/<@file:///home/idadwind/.config/ags/modules/sideright/centermodules/audiocontrols.js:18:52
hook/<@resource:///com/github/Aylur/ags/widgets/widget.js:43:25
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:263:34
  

(com.github.Aylur.ags:4904): Gjs-Console-WARNING **: 13:30:03.262: Error: can't assign "speech-dispatcher-dummy" as icon, it is not a file nor a named icon
set icon@resource:///com/github/Aylur/ags/widgets/icon.js:45:30
AppVolume/setup/<@file:///home/idadwind/.config/ags/modules/sideright/centermodules/audiocontrols.js:18:52
hook/<@resource:///com/github/Aylur/ags/widgets/widget.js:43:25
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:263:34
  

(com.github.Aylur.ags:4904): Gjs-Console-WARNING **: 13:30:03.264: Error: can't assign "speech-dispatcher-dummy" as icon, it is not a file nor a named icon
set icon@resource:///com/github/Aylur/ags/widgets/icon.js:45:30
AppVolume/setup/<@file:///home/idadwind/.config/ags/modules/sideright/centermodules/audiocontrols.js:18:52
hook/id<@resource:///com/github/Aylur/ags/widgets/widget.js:36:21
changed@resource:///com/github/Aylur/ags/service.js:53:14
setStream/this._ids</<@resource:///com/github/Aylur/ags/service/audio.js:45:22
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:263:34
  

(com.github.Aylur.ags:4904): Gjs-Console-WARNING **: 13:30:03.264: Error: can't assign "speech-dispatcher-dummy" as icon, it is not a file nor a named icon
set icon@resource:///com/github/Aylur/ags/widgets/icon.js:45:30
AppVolume/setup/<@file:///home/idadwind/.config/ags/modules/sideright/centermodules/audiocontrols.js:18:52
hook/id<@resource:///com/github/Aylur/ags/widgets/widget.js:36:21
changed@resource:///com/github/Aylur/ags/service.js:53:14
setStream/this._ids</<@resource:///com/github/Aylur/ags/service/audio.js:45:22
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:263:34
  

(com.github.Aylur.ags:4904): Gjs-Console-WARNING **: 13:30:03.264: Error: can't assign "speech-dispatcher-dummy" as icon, it is not a file nor a named icon
set icon@resource:///com/github/Aylur/ags/widgets/icon.js:45:30
AppVolume/setup/<@file:///home/idadwind/.config/ags/modules/sideright/centermodules/audiocontrols.js:18:52
hook/id<@resource:///com/github/Aylur/ags/widgets/widget.js:36:21
changed@resource:///com/github/Aylur/ags/service.js:53:14
setStream/this._ids</<@resource:///com/github/Aylur/ags/service/audio.js:45:22
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:263:34
  

(com.github.Aylur.ags:4904): Gjs-Console-WARNING **: 13:30:03.265: Error: can't assign "speech-dispatcher-dummy" as icon, it is not a file nor a named icon
set icon@resource:///com/github/Aylur/ags/widgets/icon.js:45:30
AppVolume/setup/<@file:///home/idadwind/.config/ags/modules/sideright/centermodules/audiocontrols.js:18:52
hook/id<@resource:///com/github/Aylur/ags/widgets/widget.js:36:21
changed@resource:///com/github/Aylur/ags/service.js:53:14
setStream/this._ids</<@resource:///com/github/Aylur/ags/service/audio.js:45:22
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:263:34
  

(com.github.Aylur.ags:4904): Gjs-Console-WARNING **: 13:30:03.266: Error: can't assign "speech-dispatcher-dummy" as icon, it is not a file nor a named icon
set icon@resource:///com/github/Aylur/ags/widgets/icon.js:45:30
AppVolume/setup/<@file:///home/idadwind/.config/ags/modules/sideright/centermodules/audiocontrols.js:18:52
hook/id<@resource:///com/github/Aylur/ags/widgets/widget.js:36:21
changed@resource:///com/github/Aylur/ags/service.js:53:14
setStream/this._ids</<@resource:///com/github/Aylur/ags/service/audio.js:45:22
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:263:34
  

(com.github.Aylur.ags:4904): Gjs-Console-WARNING **: 13:30:03.266: Error: can't assign "speech-dispatcher-dummy" as icon, it is not a file nor a named icon
set icon@resource:///com/github/Aylur/ags/widgets/icon.js:45:30
AppVolume/setup/<@file:///home/idadwind/.config/ags/modules/sideright/centermodules/audiocontrols.js:18:52
hook/id<@resource:///com/github/Aylur/ags/widgets/widget.js:36:21
changed@resource:///com/github/Aylur/ags/service.js:53:14
setStream/this._ids</<@resource:///com/github/Aylur/ags/service/audio.js:45:22
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:263:34
  

(com.github.Aylur.ags:4904): Gjs-Console-WARNING **: 13:30:03.267: Error: can't assign "speech-dispatcher-dummy" as icon, it is not a file nor a named icon
set icon@resource:///com/github/Aylur/ags/widgets/icon.js:45:30
AppVolume/setup/<@file:///home/idadwind/.config/ags/modules/sideright/centermodules/audiocontrols.js:18:52
hook/id<@resource:///com/github/Aylur/ags/widgets/widget.js:36:21
changed@resource:///com/github/Aylur/ags/service.js:53:14
setStream/this._ids</<@resource:///com/github/Aylur/ags/service/audio.js:45:22
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:263:34
  

(com.github.Aylur.ags:4904): Gjs-Console-WARNING **: 13:30:03.267: Error: can't assign "speech-dispatcher-dummy" as icon, it is not a file nor a named icon
set icon@resource:///com/github/Aylur/ags/widgets/icon.js:45:30
AppVolume/setup/<@file:///home/idadwind/.config/ags/modules/sideright/centermodules/audiocontrols.js:18:52
hook/id<@resource:///com/github/Aylur/ags/widgets/widget.js:36:21
changed@resource:///com/github/Aylur/ags/service.js:53:14
setStream/this._ids</<@resource:///com/github/Aylur/ags/service/audio.js:45:22
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:263:34
  

(com.github.Aylur.ags:4904): Gjs-Console-WARNING **: 13:30:03.268: Error: can't assign "speech-dispatcher-dummy" as icon, it is not a file nor a named icon
set icon@resource:///com/github/Aylur/ags/widgets/icon.js:45:30
AppVolume/setup/<@file:///home/idadwind/.config/ags/modules/sideright/centermodules/audiocontrols.js:18:52
hook/id<@resource:///com/github/Aylur/ags/widgets/widget.js:36:21
changed@resource:///com/github/Aylur/ags/service.js:53:14
setStream/this._ids</<@resource:///com/github/Aylur/ags/service/audio.js:45:22
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:263:34
  

(com.github.Aylur.ags:4904): Gjs-Console-WARNING **: 13:30:03.269: Error: can't assign "speech-dispatcher-dummy" as icon, it is not a file nor a named icon
set icon@resource:///com/github/Aylur/ags/widgets/icon.js:45:30
AppVolume/setup/<@file:///home/idadwind/.config/ags/modules/sideright/centermodules/audiocontrols.js:18:52
hook/id<@resource:///com/github/Aylur/ags/widgets/widget.js:36:21
changed@resource:///com/github/Aylur/ags/service.js:53:14
setStream/this._ids</<@resource:///com/github/Aylur/ags/service/audio.js:45:22
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:263:34
  

(com.github.Aylur.ags:4904): Gjs-Console-WARNING **: 13:30:08.280: Error: can't assign "speech-dispatcher-dummy" as icon, it is not a file nor a named icon
set icon@resource:///com/github/Aylur/ags/widgets/icon.js:45:30
AppVolume/setup/<@file:///home/idadwind/.config/ags/modules/sideright/centermodules/audiocontrols.js:18:52
hook/id<@resource:///com/github/Aylur/ags/widgets/widget.js:36:21
changed@resource:///com/github/Aylur/ags/service.js:53:14
setStream/this._ids</<@resource:///com/github/Aylur/ags/service/audio.js:45:22
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:263:34
  

(com.github.Aylur.ags:4904): Gjs-Console-WARNING **: 13:30:08.280: Error: can't assign "speech-dispatcher-dummy" as icon, it is not a file nor a named icon
set icon@resource:///com/github/Aylur/ags/widgets/icon.js:45:30
AppVolume/setup/<@file:///home/idadwind/.config/ags/modules/sideright/centermodules/audiocontrols.js:18:52
hook/id<@resource:///com/github/Aylur/ags/widgets/widget.js:36:21
changed@resource:///com/github/Aylur/ags/service.js:53:14
setStream/this._ids</<@resource:///com/github/Aylur/ags/service/audio.js:45:22
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:263:34
  

(com.github.Aylur.ags:4904): Gjs-CRITICAL **: 13:32:49.435: JS ERROR: TypeError: section.get_file() is null
applyCss/<@resource:///com/github/Aylur/ags/app.js:73:34
applyCss@resource:///com/github/Aylur/ags/app.js:81:29
CoverArt/updateCover/<@file:///home/idadwind/.config/ags/modules/indicators/musiccontrols.js:218:29
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:263:34

Gtk.CssProviderError: <data>:1:0Expected a valid selector

```

</details>

**Comment by idadwind1** [comment]
Problem solved. After some messing around, I found out that sass was not installed correctly:
```
$ sass
/usr/lib/ruby/3.3.0/rubygems.rb:259:in `find_spec_for_exe': can't find gem sass-embedded (>= 0.a) with executable sass (Gem::GemNotFoundException)
	from /usr/lib/ruby/3.3.0/rubygems.rb:278:in `activate_bin_path'
	from /usr/bin/sass:25:in `<main>'
```
Running `gem install sass-embedded` solved the issue.
