### ISSUE TITLE
[Issue] AGS freeze after open any file in VLC

### ISSUE THREAD

**Issue by clsty** [end-4/dots-hyprland#279]
- **I have read the [wiki](https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting)**
- Linux distro: Arch Linux

---
## The issue

After running `pkill ags;ags`, output:
<details>
<summary>Click to expand</summary>

```plain
(com.github.Aylur.ags:45130): Gtk-WARNING **: 22:22:35.865: Theme parsing error: gtk.css:95:30: '' is not a valid color name

(com.github.Aylur.ags:45130): Gtk-WARNING **: 22:22:35.865: Theme parsing error: gtk.css:95:44: Expected a valid selector

(com.github.Aylur.ags:45130): Gtk-WARNING **: 22:22:35.865: Theme parsing error: gtk.css:96:46: Expected a valid selector

(com.github.Aylur.ags:45130): Gtk-WARNING **: 22:22:35.865: Theme parsing error: gtk.css:97:41: Expected a valid selector

(com.github.Aylur.ags:45130): Gtk-WARNING **: 22:22:35.865: Theme parsing error: gtk.css:98:47: Expected a valid selector

(com.github.Aylur.ags:45130): Gtk-WARNING **: 22:22:35.865: Theme parsing error: gtk.css:99:49: Expected a valid selector

(com.github.Aylur.ags:45130): Gtk-WARNING **: 22:22:35.865: Theme parsing error: gtk.css:100:44: Expected a valid selector

(com.github.Aylur.ags:45130): Gtk-WARNING **: 22:22:35.865: Theme parsing error: gtk.css:105:41: Expected a valid selector

(com.github.Aylur.ags:45130): Gtk-WARNING **: 22:22:35.865: Theme parsing error: gtk.css:106:43: Expected a valid selector

(com.github.Aylur.ags:45130): Gtk-WARNING **: 22:22:35.865: Theme parsing error: gtk.css:107:47: Expected a valid selector

(com.github.Aylur.ags:45130): Gtk-WARNING **: 22:22:35.865: Theme parsing error: gtk.css:108:49: Expected a valid selector

(com.github.Aylur.ags:45130): Gtk-WARNING **: 22:22:35.865: Theme parsing error: gtk.css:109:42: Expected a valid selector

(com.github.Aylur.ags:45130): Gtk-WARNING **: 22:22:35.865: Theme parsing error: gtk.css:110:44: Expected a valid selector

(com.github.Aylur.ags:45130): Gtk-WARNING **: 22:22:35.865: Theme parsing error: gtk.css:112:60: Expected a valid selector

(com.github.Aylur.ags:45130): Gtk-WARNING **: 22:22:35.865: Theme parsing error: gtk.css:113:62: Expected a valid selector

(com.github.Aylur.ags:45130): Gtk-WARNING **: 22:22:35.865: Theme parsing error: gtk.css:116:45: Expected a valid selector

(com.github.Aylur.ags:45130): Gtk-WARNING **: 22:22:35.865: Theme parsing error: gtk.css:117:55: Expected a valid selector

(com.github.Aylur.ags:45130): Gtk-WARNING **: 22:22:35.865: Theme parsing error: gtk.css:119:55: Expected a valid selector

(com.github.Aylur.ags:45130): Gtk-WARNING **: 22:22:35.865: Theme parsing error: gtk.css:120:57: Expected a valid selector

(com.github.Aylur.ags:45130): Gtk-WARNING **: 22:22:35.865: Theme parsing error: gtk.css:121:56: Expected a valid selector

(com.github.Aylur.ags:45130): Gtk-WARNING **: 22:22:35.865: Theme parsing error: gtk.css:122:58: Expected a valid selector

(com.github.Aylur.ags:45130): Gjs-WARNING **: 22:22:36.156: Unhandled promise rejection. To suppress this warning, add an error handler to your promise chain with .catch() or a try-catch block around your mysit expression. Stack trace of the failed promise:
  _init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34


Gjs-Console-Message: 22:22:36.285: [LOG] Styles loaded

(com.github.Aylur.ags:45130): Gtk-WARNING **: 22:22:36.851: Attempting to add a widget with type Ags_Scrollable to a container of type Ags_Box, but the widget is already inside a container of type Ags_Box, please remove the widget from its existing container first.

(com.github.Aylur.ags:45130): Gtk-WARNING **: 22:22:36.960: Attempting to add a widget with type Ags_Revealer to a container of type Ags_Box, but the widget is already inside a container of type Ags_Box, please remove the widget from its existing container first.
Traceback (most recent call last):
  File "/home/mys/.config/ags/scripts/color_generation/generate_colors_material.py", line 20, in <module>
    img = Image.open(sys.argv[2])
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/PIL/Image.py", line 3247, in open
    fp = builtins.open(filename, "rb")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'undefined'
Traceback (most recent call last):
  File "/home/mys/.config/ags/scripts/color_generation/generate_colors_material.py", line 20, in <module>
    img = Image.open(sys.argv[2])
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/PIL/Image.py", line 3247, in open
    fp = builtins.open(filename, "rb")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'undefined'
Error: Expected type filename for Array element but got type 'undefined'
```

</details>

Here, AGS still works as normal.

However, when I switch to VLC, press `Ctrl+O`, select a video (or audio) file and press `Enter` to open it, AGS freeze immediately, in the meantime the output shows a new line:
```plain
(com.github.Aylur.ags:45130): LIBDBUSMENU-GLIB-WARNING **: 22:22:56.607: Unable to replace properties on 0: Error getting properties for ID
```
AGS will continue to freeze until I `pkill ags;ags` again.

After its restart, it will not freeze, despite that VLC is still playing the previous opened video file.
And it will freeze again if VLC opens another file.

This phenomenon is 100% repeatable on my PC.

**Comment by end-4** [comment]
i did this 6 times
it occurred only once

**Comment by clsty** [comment]
I've tested again on latest version of this repo.

It seems that it only occurs for some files without a metadata, or with an incomplete/malformed metadata.

**Comment by clsty** [comment]
Cool, I just noticed that the problem disappeared.
Don't know why but this is fixed, either by AGS itself or by some commit in this project.

**Comment by clsty** [comment]
This happens again on the latest repo for me.
Though I'm not very sure because I have switched to `extra/hyprland`, not `aur/hyprland-git` as it crashes frequently.

**Comment by soloopooo** [comment]
> i did this 6 times it occurred only once

Use VLC to Open a DVD iso file(with DVD menu) will 100% repeat this issue.

Since DVD menu won't have a valid timestamp ( for example: 00:00/00:00 )

In this screenshot:

![图片](https://github.com/user-attachments/assets/57e82028-ad0b-4bdf-ae02-27b1bc0030d9)

**Comment by clsty** [comment]
Not happening anymore, I don't know when/why/how but it's fixed.
Closing.
