### ISSUE TITLE
[Issue] Overview widget not showing workspaces window, only the launcher

### ISSUE THREAD

**Issue by NextStep-IM** [end-4/dots-hyprland#282]
- **I have read the [wiki](https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting)**
- Linux distro: Arco Linux

---
## The issue
The workspace window does not appear when I launch the overview widget, only the app launcher.

<details>
<summary>Click to expand</summary>

![ags-bug](https://github.com/end-4/dots-hyprland/assets/140648058/8caa764b-f3b1-4d64-bc40-6c20b46a4928)

</details>

**Comment by end-4** [comment]
This happens when the Hyprland service fails to load. Are you running on sway or something?

Anyway, run `pkill ags; ags` in a terminal (`Super`+`T`) and gimme logs

**Comment by NextStep-IM** [comment]
Here you go:
```plain

Gjs-Console-Message: 11:20:56.185: [LOG] Styles loaded

(com.github.Aylur.ags:8539): Gjs-Console-WARNING **: 11:20:56.214: Window.popup is DEPRECATED. the click away functionality depends on a bug which was patched in Hyprland and it never worked on Sway anyway. to close on the esc key use self.keybind("Escape", () => App.closeWindow("window-name"))

(com.github.Aylur.ags:8539): Gjs-Console-WARNING **: 11:20:56.425: Window.popup is DEPRECATED. the click away functionality depends on a bug which was patched in Hyprland and it never worked on Sway anyway. to close on the esc key use self.keybind("Escape", () => App.closeWindow("window-name"))

(com.github.Aylur.ags:8539): Gjs-Console-WARNING **: 11:20:56.576: Window.popup is DEPRECATED. the click away functionality depends on a bug which was patched in Hyprland and it never worked on Sway anyway. to close on the esc key use self.keybind("Escape", () => App.closeWindow("window-name"))

(com.github.Aylur.ags:8539): Gjs-Console-WARNING **: 11:20:56.638: Window.popup is DEPRECATED. the click away functionality depends on a bug which was patched in Hyprland and it never worked on Sway anyway. to close on the esc key use self.keybind("Escape", () => App.closeWindow("window-name"))

(com.github.Aylur.ags:8539): Gjs-Console-WARNING **: 11:20:56.691: Window.popup is DEPRECATED. the click away functionality depends on a bug which was patched in Hyprland and it never worked on Sway anyway. to close on the esc key use self.keybind("Escape", () => App.closeWindow("window-name"))

(com.github.Aylur.ags:8539): Gjs-Console-WARNING **: 11:20:56.715: Window.popup is DEPRECATED. the click away functionality depends on a bug which was patched in Hyprland and it never worked on Sway anyway. to close on the esc key use self.keybind("Escape", () => App.closeWindow("window-name"))

(com.github.Aylur.ags:8539): Gtk-CRITICAL **: 11:20:56.726: gtk_widget_set_accel_path: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed

(com.github.Aylur.ags:8539): Gtk-CRITICAL **: 11:20:56.726: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed

(com.github.Aylur.ags:8539): Gtk-CRITICAL **: 11:20:56.727: gtk_widget_set_accel_path: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed

(com.github.Aylur.ags:8539): Gtk-CRITICAL **: 11:20:56.727: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed

(com.github.Aylur.ags:8539): Gtk-CRITICAL **: 11:20:56.727: gtk_widget_set_accel_path: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed

(com.github.Aylur.ags:8539): Gtk-CRITICAL **: 11:20:56.727: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
Traceback (most recent call last):
  File "/home/samtheradiant/.config/ags/scripts/color_generation/generate_colors_material.py", line 20, in <module>
    img = Image.open(sys.argv[2])
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/PIL/Image.py", line 3247, in open
    fp = builtins.open(filename, "rb")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'undefined'
```

**Comment by end-4** [comment]
firetruck, now i gotta make every popup fullscreen myself

**Comment by NextStep-IM** [comment]
Fixed!

**Comment by end-4** [comment]
idk how but alright if you say so
