### ISSUE TITLE
[Issue] New notification causes old notifications to reappear in sidebar, causing significant lag

### ISSUE THREAD

**Issue by AdityaRoot** [end-4/dots-hyprland#286]
- **I have read the [wiki](https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting)**
- Linux distro: Arch

---
## The issue

AGS starts off smooth and snappy

<details>
<summary>Click to expand</summary>

```plain
Paste your log here
```
 1ms ••     
•   pkill ags
 11ms ••     
•   ags -t 'overview'

(com.github.Aylur.ags:129185): Gjs-WARNING **: 23:41:24.497: Unhandled promise rejection. To suppress this warning, add an error handler to your promise chain with .catch() or a try-catch block around your await expression. Stack trace of the failed promise:
  _init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34

Gjs-Console-Message: 23:41:24.592: [LOG] Styles loaded

(com.github.Aylur.ags:129185): Gtk-WARNING **: 23:41:24.792: Attempting to add a widget with type Ags_Scrollable to a container of type Ags_Box, but the widget is already inside a container of type Ags_Box, please remove the widget from its existing container first.

(com.github.Aylur.ags:129185): Gtk-WARNING **: 23:41:24.876: Attempting to add a widget with type Ags_Revealer to a container of type Ags_Box, but the widget is already inside a container of type Ags_Box, please remove the widget from its existing container first.
Traceback (most recent call last):
  File "/home/adi/.config/ags/scripts/color_generation/generate_colors_material.py", line 20, in <module>
    img = Image.open(sys.argv[2])
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/PIL/Image.py", line 3247, in open
    fp = builtins.open(filename, "rb")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'undefined'
Traceback (most recent call last):
  File "/home/adi/.config/ags/scripts/color_generation/generate_colors_material.py", line 20, in <module>
    img = Image.open(sys.argv[2])
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/PIL/Image.py", line 3247, in open
    fp = builtins.open(filename, "rb")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'undefined'
Traceback (most recent call last):
  File "/home/adi/.config/ags/scripts/color_generation/generate_colors_material.py", line 20, in <module>
    img = Image.open(sys.argv[2])
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/PIL/Image.py", line 3309, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file '/home/adi/.cache/ags/media/38e7aef4a9adb4ae191ee22105e44be30239d5ca'
Traceback (most recent call last):
  File "/home/adi/.config/ags/scripts/color_generation/generate_colors_material.py", line 20, in <module>
    img = Image.open(sys.argv[2])
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/PIL/Image.py", line 3309, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file '/home/adi/.cache/ags/media/38e7aef4a9adb4ae191ee22105e44be30239d5ca'
SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
^[[27;9    
</details>

**Comment by end-4** [comment]
## Notifications
- In theory should work, but results are inconsistent. sometimes AGS' notification clear does work and other times it won't work. guess i should
  - [ ] loop and destroy the widgets myself when clearing
## The log
scrollable... i guess that's due to either the music info or window title thing

**Comment by end-4** [comment]
i fixed notification clear
i also previously eliminated the lag of the music controls widget, which is the laggiest thing i know
can you check if things are alright now?

**Comment by AdityaRoot** [comment]
Same issue I'm afraid - music widget does seem significantly less laggy though!

Is there a way I can provide some sort of more helpful trace of the notification panel as I clear notifs, if it's an isolated issue on my side?

**Comment by end-4** [comment]
> Is there a way I can provide some sort of more helpful trace of the notification panel as I clear notifs, if it's an isolated issue on my side?

Just run ags in terminal and provide logs? Didn't the above commit fix it?

**Comment by AdityaRoot** [comment]
To be fair I did take a bit of a shortcut and instead simply copied over the sideright/notificationlist.js commit and updated it to the latest version of the file, I'll try updating the config entirely and try again.
