### ISSUE TITLE
[Issue] New commits caused a problem. The widgets have lost their styling.

### ISSUE THREAD

**Issue by NextStep-IM** [end-4/dots-hyprland#291]
- **I have read the [wiki](https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting)**
- Linux distro: Arco Linux

---
## The issue
I just updated to the newest commits and every widget seems to have lost its styling. Changing wallpaper (which changes colorscheme) seems to solve the problem but the widgets lose their styling again if I restart ags.

<details>
<summary>Click to expand</summary>

![ags-bug](https://github.com/end-4/dots-hyprland/assets/140648058/ad88f81d-44b1-49c7-b906-addb26fef131)
![ags-bug-2](https://github.com/end-4/dots-hyprland/assets/140648058/112fbb89-7a40-40a4-929e-7f0d224fb0ab)

```plain
rm: cannot remove '/home/samtheradiant/.cache/ags/media/latex/*': No such file or directory

(com.github.Aylur.ags:67052): Gjs-Console-WARNING **: 22:48:30.023: Window.popup is DEPRECATED. the click away functionality depends on a bug which was patched in Hyprland and it never worked on Sway anyway. to close on the esc key use self.keybind("Escape", () => App.closeWindow("window-name"))

(com.github.Aylur.ags:67052): Gjs-Console-WARNING **: 22:48:30.112: Window.popup is DEPRECATED. the click away functionality depends on a bug which was patched in Hyprland and it never worked on Sway anyway. to close on the esc key use self.keybind("Escape", () => App.closeWindow("window-name"))

(com.github.Aylur.ags:67052): Gjs-Console-WARNING **: 22:48:30.137: Window.popup is DEPRECATED. the click away functionality depends on a bug which was patched in Hyprland and it never worked on Sway anyway. to close on the esc key use self.keybind("Escape", () => App.closeWindow("window-name"))

(com.github.Aylur.ags:67052): Gjs-Console-WARNING **: 22:48:30.167: Window.popup is DEPRECATED. the click away functionality depends on a bug which was patched in Hyprland and it never worked on Sway anyway. to close on the esc key use self.keybind("Escape", () => App.closeWindow("window-name"))

(com.github.Aylur.ags:67052): Gjs-Console-WARNING **: 22:48:30.182: Window.popup is DEPRECATED. the click away functionality depends on a bug which was patched in Hyprland and it never worked on Sway anyway. to close on the esc key use self.keybind("Escape", () => App.closeWindow("window-name"))

(com.github.Aylur.ags:67052): Gjs-Console-WARNING **: 22:48:30.193: Window.popup is DEPRECATED. the click away functionality depends on a bug which was patched in Hyprland and it never worked on Sway anyway. to close on the esc key use self.keybind("Escape", () => App.closeWindow("window-name"))
GLib.SpawnError: Failed to execute child process “sass” (No such file or directory)

(com.github.Aylur.ags:67052): Gtk-CRITICAL **: 22:48:30.208: gtk_widget_set_accel_path: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed

(com.github.Aylur.ags:67052): Gtk-CRITICAL **: 22:48:30.208: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed

(com.github.Aylur.ags:67052): Gtk-CRITICAL **: 22:48:30.208: gtk_widget_set_accel_path: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed

(com.github.Aylur.ags:67052): Gtk-CRITICAL **: 22:48:30.208: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed

(com.github.Aylur.ags:67052): Gtk-CRITICAL **: 22:48:30.208: gtk_widget_set_accel_path: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed

(com.github.Aylur.ags:67052): Gtk-CRITICAL **: 22:48:30.208: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed

(com.github.Aylur.ags:67052): GdkPixbuf-CRITICAL **: 22:48:30.556: gdk_pixbuf_new_from_file_at_scale: assertion 'width > 0 || width == -1' failed
Traceback (most recent call last):
  File "/home/samtheradiant/.config/ags/scripts/color_generation/generate_colors_material.py", line 20, in <module>
    img = Image.open(sys.argv[2])
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/PIL/Image.py", line 3247, in open
    fp = builtins.open(filename, "rb")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'undefined'
Traceback (most recent call last):
  File "/home/samtheradiant/.config/ags/scripts/color_generation/generate_colors_material.py", line 20, in <module>
    img = Image.open(sys.argv[2])
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/PIL/Image.py", line 3247, in open
    fp = builtins.open(filename, "rb")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'undefined'
Error: Expected type filename for Array element but got type 'undefined'
```

</details>

**Comment by daUnknownCoder** [comment]
> * **I have read the [wiki](https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting)**
> * Linux distro: Arco Linux
> 
> ## The issue
> I just updated to the newest commits and every widget seems to have lost its styling. Changing wallpaper (which changes colorscheme) seems to solve the problem but the widgets lose their styling again if I restart ags.
> 
> Click to expand

i got that for a portrait wallpaper, choose a landscape one

**Comment by NextStep-IM** [comment]
> i got that for a portrait wallpaper, choose a landscape one

No luck. Changing the wallpaper doesn't even change the colorscheme.

**Comment by end-4** [comment]
`yay -S dart-sass`

**Comment by NextStep-IM** [comment]
Fixed. Thanks, @end-4!

**Comment by daUnknownCoder** [comment]
> `yay -S dart-sass`

Hey @end-4, I have dart-sass but when I used a portrait wallpaper

![84b4b001-0d7f-43d3-920f-9b68f9ca8baa-Space%20x_5422](https://github.com/end-4/dots-hyprland/assets/84800625/5765a571-5b6b-4846-99ce-0264fd34b7e5)

This Is the same wallpaper I tried, my bar went nuts?

**Comment by end-4** [comment]
idk, give logs 
run `~/.config/ags/scripts/color_generation/switchwall.sh` in terminal

**Comment by daUnknownCoder** [comment]
> run `~/.config/ags/scripts/color_generation/switchwall.sh` in terminal
```bash
Error: expected "{".
  ╷
2 │ $darkmode: true;
  │                ^
  ╵
  scss/_material.scss 2:16  @import
  scss/main.scss 8:9        root stylesheet
undefined
Gtk.CssProviderError: style.css:9:5Invalid name of pseudo-class
[Gradience] INFO: Preset Material3_Generated applied successfully for Gtk 3 and Gtk 4 applications.
[Gradience] INFO: In order for changes to take full effect, you need to log out.
```
![image](https://github.com/end-4/dots-hyprland/assets/84800625/3fb5fccd-4175-460d-8b5d-dd668ebd1c33)

Only happens with this image, i checked with other images, they work this one doesn't, havent tried many images but why is that possibly happening?

**Comment by end-4** [comment]
can you send `~/.config/ags/scss/_material.scss`

**Comment by daUnknownCoder** [comment]
for the `hacked` wallpaper:
```scss
$darkmode: true;
$primary: #acc7ff;
$onPrimary: #002e6c;
$primaryContainer: #004397;
$onPrimaryContainer: #d6e2ff;
$secondary: #bfc6dc;
$onSecondary: #283041;
$secondaryContainer: #3f4759;
$onSecondaryContainer: #dae2f9;
$tertiary: #debbdf;
$onTertiary: #402843;
$tertiaryContainer: #583e5b;
$onTertiaryContainer: #fbd7fb;
$error: #ffb4a9;
$onError: #680003;
$errorContainer: #930006;
$onErrorContainer: #ffb4a9;
$colorbarbg: #101012;
$background: #101012;
$onBackground: #e4e2e6;
$surface: #1b1b1e;
$onSurface: #e4e2e6;
$surfaceVariant: #44474f;
$onSurfaceVariant: #c4c6d0;
$outline: #8e9099;
$shadow: #000000;
$inverseSurface: #e4e2e6;
$inverseOnSurface: #2f3033;
$inversePrimary: #005ac5;
```

for the `spacex` image:
```scss
Warning: Image not in RGB|RGBA format - Converting...
$darkmode: true;
$primary: #acc7ff;
$onPrimary: #002e6c;
$primaryContainer: #004397;
$onPrimaryContainer: #d6e2ff;
$secondary: #bfc6dc;
$onSecondary: #283041;
$secondaryContainer: #3f4759;
$onSecondaryContainer: #dae2f9;
$tertiary: #debbdf;
$onTertiary: #402843;
$tertiaryContainer: #583e5b;
$onTertiaryContainer: #fbd7fb;
$error: #ffb4a9;
$onError: #680003;
$errorContainer: #930006;
$onErrorContainer: #ffb4a9;
$colorbarbg: #101012;
$background: #101012;
$onBackground: #e4e2e6;
$surface: #1b1b1e;
$onSurface: #e4e2e6;
$surfaceVariant: #44474f;
$onSurfaceVariant: #c4c6d0;
$outline: #8e9099;
$shadow: #000000;
$inverseSurface: #e4e2e6;
$inverseOnSurface: #2f3033;
$inversePrimary: #005ac5;
```

**Comment by clsty** [comment]
Ok, so the problem seems obvious: when generating that scss, a "Warning" message blended in and messed up the file.

For solution, we may redirect the STDERR i.e. the warning message to `/dev/null`, e.g.
```bash
    color_generation/generate_colors_material.py --color "$1" "$lightdark" 1> "$HOME"/.cache/ags/user/generated/material_colors.scss 2>/dev/null
```
Here `1>` means redirecting STDOUT and `2>` means redirecting STDERR. We output them to different places.

But the solution only works when the warning message is in STDERR.

If it does not work, then we need to find another method.

---

Plus, let's reopen this issue since talking in a closed issue is kinda weird lol

**Comment by NextStep-IM** [comment]
Experienced the problem again with the latest commits.
![ags_style_bug](https://github.com/end-4/dots-hyprland/assets/140648058/9afcfee1-1d4b-4c11-b339-cc14e5875f75)
Logs:
```plain

(com.github.Aylur.ags:14156): Gjs-Console-CRITICAL **: 05:00:44.694: CSS ERROR: Invalid name of pseudo-class at line 8 in /home/samtheradiant/.cache/ags/user/generated/style.css
Gtk.CssProviderError: style.css:9:5Invalid name of pseudo-class

(com.github.Aylur.ags:14156): Gtk-CRITICAL **: 05:00:44.968: gtk_widget_set_accel_path: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed

(com.github.Aylur.ags:14156): Gtk-CRITICAL **: 05:00:44.968: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed

(com.github.Aylur.ags:14156): Gtk-CRITICAL **: 05:00:44.968: gtk_widget_set_accel_path: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed

(com.github.Aylur.ags:14156): Gtk-CRITICAL **: 05:00:44.968: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed

(com.github.Aylur.ags:14156): Gtk-CRITICAL **: 05:00:44.969: gtk_widget_set_accel_path: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed

(com.github.Aylur.ags:14156): Gtk-CRITICAL **: 05:00:44.969: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
Traceback (most recent call last):
  File "/home/samtheradiant/.config/ags/scripts/color_generation/generate_colors_material.py", line 20, in <module>
    img = Image.open(sys.argv[2])
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/PIL/Image.py", line 3247, in open
    fp = builtins.open(filename, "rb")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'undefined'
```

**Comment by NextStep-IM** [comment]
Aaaaand now its fixed.

**Comment by UcraNerd** [comment]
> Aaaaand now its fixed.

If it's fixed don't you think that the issue should be closed?

**Comment by NextStep-IM** [comment]
> If it's fixed don't you think that the issue should be closed?

It fixed itself and I have no idea how. So I left it to end_4 judgement.

**Comment by daUnknownCoder** [comment]
yo this still happens: #428
