### ISSUE TITLE
[Issue] Latest commits caused widgets' style loss and hyprland error

### ISSUE THREAD

**Issue by NextStep-IM** [end-4/dots-hyprland#366]
- **(For usage) I have read the [wiki](https://end-4.github.io/dots-hyprland-wiki/en/i-i/02usage)**
- **(For troubleshooting) I have read the [wiki](https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting)**
- Linux distro: Arco Linux
---
## The issue
Just updated to the latest commits and widget's lost their styling and hyprland gives an error. 
<details>
<summary>Click to expand</summary>

**Hyprland Error:**
```plain
Config error in file $HOME/.config/hypr/hyprland/colors.conf at line 9: rgba() expects length of 8 characters (4 bytes) or 4 comma separated values.
Config error in file $HOME/.config/hypr/hyprland.conf at line 9: Config error in file $HOME/.config/hypr/hyprland/colors.conf at line 9: rgba() expects length of 8 characters (4 bytes) or 4 comma separated values.
```
**AGS Error:**
```plain
(com.github.Aylur.ags:377994): Gtk-WARNING **: 17:19:07.722: Theme parsing error: gtk.css:95:30: '' is not a valid color name

(com.github.Aylur.ags:377994): Gtk-WARNING **: 17:19:07.722: Theme parsing error: gtk.css:95:44: Expected a valid selector

(com.github.Aylur.ags:377994): Gtk-WARNING **: 17:19:07.722: Theme parsing error: gtk.css:96:46: Expected a valid selector

(com.github.Aylur.ags:377994): Gtk-WARNING **: 17:19:07.722: Theme parsing error: gtk.css:97:41: Expected a valid selector

(com.github.Aylur.ags:377994): Gtk-WARNING **: 17:19:07.722: Theme parsing error: gtk.css:98:47: Expected a valid selector

(com.github.Aylur.ags:377994): Gtk-WARNING **: 17:19:07.722: Theme parsing error: gtk.css:99:49: Expected a valid selector

(com.github.Aylur.ags:377994): Gtk-WARNING **: 17:19:07.722: Theme parsing error: gtk.css:100:44: Expected a valid selector

(com.github.Aylur.ags:377994): Gtk-WARNING **: 17:19:07.722: Theme parsing error: gtk.css:105:41: Expected a valid selector

(com.github.Aylur.ags:377994): Gtk-WARNING **: 17:19:07.722: Theme parsing error: gtk.css:106:43: Expected a valid selector

(com.github.Aylur.ags:377994): Gtk-WARNING **: 17:19:07.722: Theme parsing error: gtk.css:107:47: Expected a valid selector

(com.github.Aylur.ags:377994): Gtk-WARNING **: 17:19:07.722: Theme parsing error: gtk.css:108:49: Expected a valid selector

(com.github.Aylur.ags:377994): Gtk-WARNING **: 17:19:07.722: Theme parsing error: gtk.css:109:42: Expected a valid selector

(com.github.Aylur.ags:377994): Gtk-WARNING **: 17:19:07.722: Theme parsing error: gtk.css:110:44: Expected a valid selector

(com.github.Aylur.ags:377994): Gtk-WARNING **: 17:19:07.722: Theme parsing error: gtk.css:112:60: Expected a valid selector

(com.github.Aylur.ags:377994): Gtk-WARNING **: 17:19:07.722: Theme parsing error: gtk.css:113:62: Expected a valid selector

(com.github.Aylur.ags:377994): Gtk-WARNING **: 17:19:07.722: Theme parsing error: gtk.css:116:45: Expected a valid selector

(com.github.Aylur.ags:377994): Gtk-WARNING **: 17:19:07.722: Theme parsing error: gtk.css:117:55: Expected a valid selector

(com.github.Aylur.ags:377994): Gtk-WARNING **: 17:19:07.722: Theme parsing error: gtk.css:119:55: Expected a valid selector

(com.github.Aylur.ags:377994): Gtk-WARNING **: 17:19:07.722: Theme parsing error: gtk.css:120:57: Expected a valid selector

(com.github.Aylur.ags:377994): Gtk-WARNING **: 17:19:07.722: Theme parsing error: gtk.css:121:56: Expected a valid selector

(com.github.Aylur.ags:377994): Gtk-WARNING **: 17:19:07.722: Theme parsing error: gtk.css:122:58: Expected a valid selector


(com.github.Aylur.ags:377994): Gjs-Console-CRITICAL **: 17:19:08.539: CSS ERROR: Invalid name of pseudo-class at line 8 in /home/samtheradiant/.cache/ags/user/generated/style.css
Gtk.CssProviderError: style.css:9:5Invalid name of pseudo-class

(com.github.Aylur.ags:377994): Gtk-CRITICAL **: 17:19:08.770: gtk_widget_set_accel_path: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed

(com.github.Aylur.ags:377994): Gtk-CRITICAL **: 17:19:08.770: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed

(com.github.Aylur.ags:377994): Gtk-CRITICAL **: 17:19:08.770: gtk_widget_set_accel_path: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed

(com.github.Aylur.ags:377994): Gtk-CRITICAL **: 17:19:08.770: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed

(com.github.Aylur.ags:377994): Gtk-CRITICAL **: 17:19:08.771: gtk_widget_set_accel_path: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed

(com.github.Aylur.ags:377994): Gtk-CRITICAL **: 17:19:08.771: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
Traceback (most recent call last):
  File "/home/samtheradiant/.config/ags/scripts/color_generation/generate_colors_material.py", line 44, in <module>
    image = Image.open(args.path)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/PIL/Image.py", line 3247, in open
    fp = builtins.open(filename, "rb")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'undefined'
^C
❯ z hyprland
❯ z hyprland
❯ z hyprland
❯ ea
 colors.conf   env.conf   execs.conf   general.conf   keybinds.conf   rules.conf
❯ nvim colors.conf
❯ pkill ags; ags

(com.github.Aylur.ags:394417): Gtk-WARNING **: 17:22:40.125: Theme parsing error: gtk.css:95:30: '' is not a valid color name

(com.github.Aylur.ags:394417): Gtk-WARNING **: 17:22:40.125: Theme parsing error: gtk.css:95:44: Expected a valid selector

(com.github.Aylur.ags:394417): Gtk-WARNING **: 17:22:40.125: Theme parsing error: gtk.css:96:46: Expected a valid selector

(com.github.Aylur.ags:394417): Gtk-WARNING **: 17:22:40.125: Theme parsing error: gtk.css:97:41: Expected a valid selector

(com.github.Aylur.ags:394417): Gtk-WARNING **: 17:22:40.125: Theme parsing error: gtk.css:98:47: Expected a valid selector

(com.github.Aylur.ags:394417): Gtk-WARNING **: 17:22:40.125: Theme parsing error: gtk.css:99:49: Expected a valid selector

(com.github.Aylur.ags:394417): Gtk-WARNING **: 17:22:40.125: Theme parsing error: gtk.css:100:44: Expected a valid selector

(com.github.Aylur.ags:394417): Gtk-WARNING **: 17:22:40.125: Theme parsing error: gtk.css:105:41: Expected a valid selector

(com.github.Aylur.ags:394417): Gtk-WARNING **: 17:22:40.125: Theme parsing error: gtk.css:106:43: Expected a valid selector

(com.github.Aylur.ags:394417): Gtk-WARNING **: 17:22:40.125: Theme parsing error: gtk.css:107:47: Expected a valid selector

(com.github.Aylur.ags:394417): Gtk-WARNING **: 17:22:40.125: Theme parsing error: gtk.css:108:49: Expected a valid selector

(com.github.Aylur.ags:394417): Gtk-WARNING **: 17:22:40.125: Theme parsing error: gtk.css:109:42: Expected a valid selector

(com.github.Aylur.ags:394417): Gtk-WARNING **: 17:22:40.126: Theme parsing error: gtk.css:110:44: Expected a valid selector

(com.github.Aylur.ags:394417): Gtk-WARNING **: 17:22:40.126: Theme parsing error: gtk.css:112:60: Expected a valid selector

(com.github.Aylur.ags:394417): Gtk-WARNING **: 17:22:40.126: Theme parsing error: gtk.css:113:62: Expected a valid selector

(com.github.Aylur.ags:394417): Gtk-WARNING **: 17:22:40.126: Theme parsing error: gtk.css:116:45: Expected a valid selector

(com.github.Aylur.ags:394417): Gtk-WARNING **: 17:22:40.126: Theme parsing error: gtk.css:117:55: Expected a valid selector

(com.github.Aylur.ags:394417): Gtk-WARNING **: 17:22:40.126: Theme parsing error: gtk.css:119:55: Expected a valid selector

(com.github.Aylur.ags:394417): Gtk-WARNING **: 17:22:40.126: Theme parsing error: gtk.css:120:57: Expected a valid selector

(com.github.Aylur.ags:394417): Gtk-WARNING **: 17:22:40.126: Theme parsing error: gtk.css:121:56: Expected a valid selector

(com.github.Aylur.ags:394417): Gtk-WARNING **: 17:22:40.126: Theme parsing error: gtk.css:122:58: Expected a valid selector


(com.github.Aylur.ags:394417): Gjs-Console-CRITICAL **: 17:22:40.983: CSS ERROR: Invalid name of pseudo-class at line 8 in /home/samtheradiant/.cache/ags/user/generated/style.css
Gtk.CssProviderError: style.css:9:5Invalid name of pseudo-class

(com.github.Aylur.ags:394417): Gtk-CRITICAL **: 17:22:41.193: gtk_widget_set_accel_path: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed

(com.github.Aylur.ags:394417): Gtk-CRITICAL **: 17:22:41.193: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed

(com.github.Aylur.ags:394417): Gtk-CRITICAL **: 17:22:41.193: gtk_widget_set_accel_path: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed

(com.github.Aylur.ags:394417): Gtk-CRITICAL **: 17:22:41.194: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed

(com.github.Aylur.ags:394417): Gtk-CRITICAL **: 17:22:41.194: gtk_widget_set_accel_path: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed

(com.github.Aylur.ags:394417): Gtk-CRITICAL **: 17:22:41.194: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
Traceback (most recent call last):
  File "/home/samtheradiant/.config/ags/scripts/color_generation/generate_colors_material.py", line 44, in <module>
    image = Image.open(args.path)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/PIL/Image.py", line 3247, in open
    fp = builtins.open(filename, "rb")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'undefined'
```

</details>

**Comment by clsty** [comment]
@end-4 Seems likes related to this [comment](https://github.com/end-4/dots-hyprland/commit/c62d771f3855ca939cec85c283dbbaa3abc2f2e4#r140331320)

**Comment by NextStep-IM** [comment]
Changing the line fixed it. Thanks, @clsty!
