### ISSUE TITLE
[Issue] Can't access .local/state/ags from regular user

### ISSUE THREAD

**Issue by l4v3nx** [end-4/dots-hyprland#519]
- **I have read the [Usage](https://end-4.github.io/dots-hyprland-wiki/en/i-i/02usage) and the [Troubleshooting](https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting) pages of the wiki**
- **I have made sure that both my config and system packages are up to date**
- Linux distro: Arch Linux

---
## The issue

When trying to access .local/state/ags from regular user, it says i have no permissions. This is probably the reason why .config/hypr/hyprland/colors.conf and .config/fuzzel/fuzzel.ini fuck up after toggling transparency  # from sideright (showing variable name instead of actual color). Also, i have the same issue as in #518 (maybe this is somehow related to this issue)

<details>
<summary>Click to expand</summary>

```plain
-> % ls .local/state/ags 
ls: cannot open directory '.local/state/ags': Permission denied
```

```plain
-> % stat .local/state/ags
  File: .local/state/ags
  Size: 16        	Blocks: 0          IO Block: 4096   directory
Device: 0,38	Inode: 29616458    Links: 1
Access: (1341/d-wxr----t)  Uid: ( 1000/old4ever)   Gid: ( 1000/old4ever)
Access: 2024-05-20 18:09:38.230907721 +0300
Modify: 2024-05-20 18:09:38.897574776 +0300
Change: 2024-05-20 18:09:38.897574776 +0300
 Birth: 2024-05-20 18:09:38.230907721 +0300
```
```
.config/hypr/hyprland/colors.conf (after toggling transparency)
====================================
# exec = export SLURP_ARGS='-d -c {{ $onSecondaryContainer }}BB -b {{ $secondaryContainer }}44 -s 00000000'

general {
    col.active_border = rgba({{ $onSurface }}39)
    col.inactive_border = rgba({{ $outline }}30)
}

misc {
    background_color = rgba({{ $surface }}FF)
}

plugin {
    hyprbars {
        # Honestly idk if it works like css, but well, why not
        bar_text_font = Rubik, Geist, AR One Sans, Reddit Sans, Inter, Roboto, Ubuntu, Noto Sans, sans-serif
        bar_height = 30
        bar_padding = 10
        bar_button_padding = 5
        bar_precedence_over_border = true
        bar_part_of_window = true

        bar_color = rgba({{ $background }}FF)
        col.text = rgba({{ $onBackground }}FF)


        # example buttons (R -> L)
        # hyprbars-button = color, size, on-click
        hyprbars-button = rgb({{ $onBackground }}), 13, <U+F05AD>, hyprctl dispatch killactive
        hyprbars-button = rgb({{ $onBackground }}), 13, <U+F05AF>, hyprctl dispatch fullscreen 1
        hyprbars-button = rgb({{ $onBackground }}), 13, <U+F05B0>, hyprctl dispatch movetoworkspacesilent special
    }
}

windowrulev2 = bordercolor rgba({{ $primary }}AA) rgba({{ $primary }}77),pinned:1
```

```
.config/fuzzel/fuzzel.ini (after toggling transparency)
==================================
font=Gabarito
terminal=foot -e
prompt=">>  "
layer=overlay

[colors]
background={{ $background }}ff
text={{ $onBackground }}ff
selection={{ $surfaceVariant }}ff
selection-text={{ $onSurfaceVariant }}ff
border={{ $surfaceVariant }}dd
match={{ $primary }}ff
selection-match={{ $primary }}ff


[border]
radius=17
width=1

[dmenu]
exit-immediately-if-empty=yes
```

</details>

**Comment by end-4** [comment]
logs of `~/.config/ags/scripts/color_generation/switchwall.sh --noswitch` pls

**Comment by l4v3nx** [comment]
```plain
undefined
Traceback (most recent call last):
  File "/usr/bin/gradience-cli", line 557, in <module>
    cli = CLI()
          ^^^^^
  File "/usr/bin/gradience-cli", line 141, in __init__
    self.__parse_args()
  File "/usr/bin/gradience-cli", line 165, in __parse_args
    self.apply_preset(args)
  File "/usr/bin/gradience-cli", line 309, in apply_preset
    PresetUtils().apply_preset("gtk4", preset)
  File "/usr/lib/python3.12/site-packages/gradience/backend/theming/preset.py", line 136, in apply_preset
    with open(gtk_css_path, "w", encoding="utf-8") as css_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/home/old4ever/.config/gtk-4.0/gtk.css'
undefined
```
btw i have catppuccin gtk theme installed (aur package and link .config/gtk-4.0/gtk.css -> /usr/share/themes/Catppuccin-Mocha-Standard-Mauve-Dark/gtk-4.0/gtk.css. Maybe that's the problem

**Comment by l4v3nx** [comment]
i deleted those links and now everything is fine except #518 (transparency still doesn't apply)

**Comment by l4v3nx** [comment]
btw clicking any buttons in super+comma dosen't show any difference in color scheme preview

https://github.com/end-4/dots-hyprland/assets/58698398/d69f7300-ad2b-4719-9516-80fc6c972823

**Comment by H0mire** [comment]
#524
