### ISSUE TITLE
Applying a theme only affects the currently running kitty instances

### ISSUE THREAD

**Issue by doomed-neko** [end-4/dots-hyprland#980]
- I have read the Usage and Troubleshooting pages of the wiki: https://end-4.github.io/dots-hyprland-wiki/en/i-i/04troubleshooting/
- I have made sure that both my config and system packages are up to date
- Linux distro:  Arch linux (btw)

---
## The issue

Whenever I apply a new wallpaper, colors are applied automatically for my apps, including kitty
but the problem is that the colors only apply to kitty instances that are running prior to changing the wallpaper, all new instances use the default theme.

<details>
<summary>Logs</summary>

```plain
I don't know which logs to post, if any are required then you can tell me and I'll add them here
```

</details>

**Comment by g-verdex** [comment]
Same thing, After upgrading all utilities at once, gtk3.0 and gtk4 settings are not getting hooked up by changing wallpaper utility, only terminal colors for fonts for some weird reason do

**Comment by g-verdex** [comment]
I found the problem, in my case gtk4 in .config was immutable  ` /home/verdex/.config/ags/scripts/color_generation/switchwall.sh 

(yad:82937): Gtk-WARNING **: 09:28:04.158: Attempting to read the recently used resources file at '/home/verdex/.local/share/recently-used.xbel', but the parser failed: Failed to open file “/home/verdex/.local/share/recently-used.xbel”: Permission denied.
   ~/Pictures                                                                                                                                                     6s
❯ 
SVG colors have been updated and saved to /home/verdex/.config/Kvantum/MaterialAdw/MaterialAdw.svg!
Config colors updated successfully!
Traceback (most recent call last):
  File "/home/verdex/.local/state/ags/.venv/bin/gradience-cli", line 557, in <module>
    cli = CLI()
          ^^^^^
  File "/home/verdex/.local/state/ags/.venv/bin/gradience-cli", line 141, in __init__
    self.__parse_args()
  File "/home/verdex/.local/state/ags/.venv/bin/gradience-cli", line 165, in __parse_args
    self.apply_preset(args)
  File "/home/verdex/.local/state/ags/.venv/bin/gradience-cli", line 309, in apply_preset
    PresetUtils().apply_preset("gtk4", preset)
  File "/home/verdex/.local/state/ags/.venv/lib/python3.12/site-packages/gradience/backend/theming/preset.py", line 136, in apply_preset
    with open(gtk_css_path, "w", encoding="utf-8") as css_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 1] Operation not permitted: '/home/verdex/.config/gtk-4.0/gtk.css'
`

**Comment by g-verdex** [comment]
Solution was
1. locate switchwall.sh 
2. execute from terminal, then try to switchwall
3. fix permissions chown -R $USER:$USER ~/.config/gtk* && chmod 644 ~/.config/gtk* (use chattr -i if file is immutable) 
4. re-run script

**Comment by ChorusCory** [comment]
this doesn't help at all 4 me, lol

**Comment by g-verdex** [comment]
> this doesn't help at all 4 me, lol

please, invoke switchwall.sh  manually and provide output

**Comment by ChorusCory** [comment]
`./switchwall.sh: line 35: cd: /home/corys/Pictures/Wallpapers: No such file or directory
[corys@yuribox color_generation]$ SVG colors have been updated and saved to /home/corys/.config/Kvantum/MaterialAdw/MaterialAdw.svg!
Config colors updated successfully!

undefined
[Gradience] DEBUG: No translated schema for org.gnome.desktop.interface (domain: gsettings-desktop-schemas)
[Gradience] DEBUG: Caching gsettings: <gradience._GSettingsSchema: org.gnome.desktop.interface>
[Gradience] INFO: Preset Material3_Generated applied successfully for Gtk 3 and Gtk 4 applications.
[Gradience] INFO: In order for changes to take full effect, you need to log out.
undefined`

**Comment by end-4** [comment]
Color change only applies on start if it's fish shell because only fish is configured to apply the colors
Just to be sure, you were using some non-fish shell right?
5281009d38d1810a9d37b7fc4125605f5184ac79 made kitty use fish shell. with this change your shell in kitty should be fish and it should work

**Comment by ChorusCory** [comment]
yes, i was using bash before, and now everything works fine. thanks!
